version: '3.7'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: backend/
    env_file: .env
    command: sh -c "alembic upgrade head &&
                    uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on:
      - db
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/${BUCKET};
      /usr/bin/mc policy set public minio/${BUCKET};
      exit 0;
      "
volumes:
  minio-storage:
  postgres_data:
