name: Main Meme_Collection Workflow
on:
  push:
    branches:
      - main
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt
    - name: Check with flake8
      run: python -m flake8 --exclude backend/alembic/ backend/
  tests:
    needs: linters
    runs-on: ubuntu-latest
    services:
      s3:
        image: minio/minio:edge-cicd
        options: --health-cmd "curl -s http://localhost:9000/minio/health/live"
        env:
            MINIO_ROOT_USER: dev
            MINIO_ROOT_PASSWORD: admindev
    steps:
      - name: Fetch mc client
        run: curl -o ./mc -# https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc
      - name: Create the dev bucket
        run: ./mc alias set minio http://s3:9000 dev admindev && ./mc mb minio/dev-bucket
      - name: Remove mc client
        run: rm -v ./mc
      - name: Fetch mc client
        run: curl -o ./mc -# https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc
      - name: Create the dev bucket
        run: ./mc alias set minio http://s3:9000 minio_dev minio_password_dev && ./mc mb minio/dev-bucket
      - name: Remove mc client
        run: rm -v ./mc
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Start tests
        run: |
          touch .env
          echo ENDPOINT=minio:9000 >> .env
          echo API_ENDPOINT=${{ secrets.API_ENDPOINT }} >> .env
          echo ACCESS_KEY=minio_dev >> .env
          echo SECRET_KEY=minio_password_dev >> .env
          echo BUCKET=dev-bucket >> .env
          cat .env
          cd backend/
          cd ..
          cd tests/
          python -m pytest
